version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - BRANCH=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d/ -f3)
      - |
        if [ "$BRANCH_NAME" = "main" ]; then
          IMAGE_TAG="prd-${CODEBUILD_RESOLVED_SOURCE_VERSION}"
        elif [ "$BRANCH_NAME" = "develop" ]; then
          IMAGE_TAG="dev-${CODEBUILD_RESOLVED_SOURCE_VERSION}"
        else
          IMAGE_TAG="other-${CODEBUILD_RESOLVED_SOURCE_VERSION}"
        fi;
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION \
        | docker login \
        --username $AWS_USERNAME \
        --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - |
        if [ "$BRANCH_NAME" = "main" ]; then
          REPOSITORY_NAME="$PRD_REPOSITORY_NAME"
        elif [ "$BRANCH_NAME" = "develop" ]; then
          REPOSITORY_NAME="$DEV_REPOSITORY_NAME"
        else
          REPOSITORY_NAME="$DEV_REPOSITORY_NAME"
        fi;
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - DOCKER_CONTAINER_NAME=golang-pipeline-aws
      - printf '[{"name":"%s","book-finder-api":"%s"}]' \
        $DOCKER_CONTAINER_NAME \
        $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
